---
# tasks file for whirm.dispersy_runner

#TODO move most of the deps to tribler_runner.yml as those are needed by tribler, not dispersy.

- name: install dispersy dependencies
  action: apt pkg={{item}} state=present
  with_items:
    - dpkg-dev
    - libav-tools
    - libjs-excanvas
    - libjs-mootools
    - libleveldb-dev
    - libpython2.7-dev
    - libsodium13
    - libstdc++6-4.8-dbg
    - libx11-6
    - python2.7
    - python-apsw
    - python-configobj
    - python-cryptography
    - python-dbg
    - python-gmpy
    - python-leveldb
    - python-m2crypto
    - python-netifaces
    - python-pil
    - python-pip
    - python-pyasn1
    - python-requests
    - python-twisted
    - python-twisted-bin-dbg
    - python-virtualenv
    - python-zope.interface-dbg
